<a href="https://colab.research.google.com/github/souptiks/Decision-Tree/blob/main/Company_Hiring_Data_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Company_Hiring_DataSet.csv")

In [ ]:
df

,Company Size,Industry,Revenue,Location,Employee Turnover Rate,Employee Skillset,Job Openings,Recruitment Budget,Company Age,Growth Rate,Likely to Hire
0,150,Technology,50000000,San Francisco,10,Python,10,50000,5,8,Yes
1,300,Healthcare,8000000,New York,5,Java,5,30000,10,5,No
2,75,Finance,20000000,London,8,SQL,8,40000,3,12,Yes
3,200,Technology,35000000,Bangalore,12,C++,15,60000,7,10,Yes
4,100,Finance,15000000,Chicago,6,Management,3,20000,4,6,No
...,...,...,...,...,...,...,...,...,...,...,...
1321,250,Technology,62000000,Paris,16,JavaScript,28,70000,9,12,Yes
1322,380,Finance,39000000,Berlin,19,SQL,25,56000,8,13,Yes
1323,200,Healthcare,10100000,Madrid,14,Java,22,55000,13,8,Yes
1324,350,Technology,103000000,Amsterdam,17,Python,33,81000,10,13,Yes
1325,110,Finance,32000000,Rome,20,Management,27,38000,8,11,Yes

In [ ]:
inputs = df.drop('Likely to Hire',axis='columns')
target = df['Likely to Hire']

In [ ]:
inputs

,Company Size,Industry,Revenue,Location,Employee Turnover Rate,Employee Skillset,Job Openings,Recruitment Budget,Company Age,Growth Rate
0,150,Technology,50000000,San Francisco,10,Python,10,50000,5,8
1,300,Healthcare,8000000,New York,5,Java,5,30000,10,5
2,75,Finance,20000000,London,8,SQL,8,40000,3,12
3,200,Technology,35000000,Bangalore,12,C++,15,60000,7,10
4,100,Finance,15000000,Chicago,6,Management,3,20000,4,6
...,...,...,...,...,...,...,...,...,...,...
1321,250,Technology,62000000,Paris,16,JavaScript,28,70000,9,12
1322,380,Finance,39000000,Berlin,19,SQL,25,56000,8,13
1323,200,Healthcare,10100000,Madrid,14,Java,22,55000,13,8
1324,350,Technology,103000000,Amsterdam,17,Python,33,81000,10,13
1325,110,Finance,32000000,Rome,20,Management,27,38000,8,11

In [ ]:
target

0       Yes
1        No
2       Yes
3       Yes
4        No
       ...
1321    Yes
1322    Yes
1323    Yes
1324    Yes
1325    Yes
Name: Likely to Hire, Length: 1326, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
LabelEncoder()

LabelEncoder()

In [ ]:
le_Company_Size	= LabelEncoder()
le_Industry = LabelEncoder()
le_Revenue = LabelEncoder()
le_Location = LabelEncoder()
le_Employee_Turnover_Rate = LabelEncoder()
le_Employee_Skillset = LabelEncoder()
le_Job_Openings = LabelEncoder()
le_Recruitment_Budget = LabelEncoder()
le_Company_Age = LabelEncoder()
le_Growth_Rate = LabelEncoder()

In [ ]:
inputs['Company Size'] = le_Company_Size.fit_transform(inputs['Company Size'])
inputs['Industry'] = le_Industry.fit_transform(inputs['Industry'])
inputs['Revenue'] = le_Revenue.fit_transform(inputs['Revenue'])
inputs['Location'] = le_Location.fit_transform(inputs['Location'])
inputs['Employee Turnover Rate'] = le_Employee_Turnover_Rate.fit_transform(inputs['Employee Turnover Rate'])
inputs['Employee Skillset'] = le_Employee_Skillset.fit_transform(inputs['Employee Skillset'])
inputs['Job Openings'] = le_Job_Openings.fit_transform(inputs['Job Openings'])
inputs['Recruitment Budget'] = le_Recruitment_Budget.fit_transform(inputs['Recruitment Budget'])
inputs['Company Age'] = le_Company_Age.fit_transform(inputs['Company Age'])
inputs['Growth Rate'] = le_Growth_Rate.fit_transform(inputs['Growth Rate'])
inputs.head()

,Company Size,Industry,Revenue,Location,Employee Turnover Rate,Employee Skillset,Job Openings,Recruitment Budget,Company Age,Growth Rate
0,9,5,66,286,8,7,7,26,2,5
1,25,3,13,229,3,4,2,6,7,2
2,0,1,39,182,6,9,5,16,0,9
3,15,5,51,28,10,0,12,36,4,7
4,4,1,34,71,4,6,0,0,1,3

In [ ]:
from sklearn import tree

In [ ]:
model = tree.DecisionTreeClassifier()

In [ ]:
model.fit(inputs,target)

DecisionTreeClassifier()

In [ ]:
import numpy as np

# Your original 1D array
data = np.array([4,1,34,71,4,6,0,0,1,3])

# Reshape to 2D array for a single sample
data_2d = data.reshape(1, -1)

# Now you can use this 2D array for prediction
model.predict(data_2d)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['No'], dtype=object)